//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class shipment {
    
    private string documentNameField;
    
    private string shipmentNumberField;
    
    private string shippingDateField;
    
    private string transportModeIdField;
    
    private string brokerIdField;
    
    private string senderDescField;
    
    private string senderFiscalCodeField;
    
    private string hubDescField;
    
    private shipmentVoyage[] voyageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string documentName {
        get {
            return this.documentNameField;
        }
        set {
            this.documentNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shipmentNumber {
        get {
            return this.shipmentNumberField;
        }
        set {
            this.shipmentNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shippingDate {
        get {
            return this.shippingDateField;
        }
        set {
            this.shippingDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string transportModeId {
        get {
            return this.transportModeIdField;
        }
        set {
            this.transportModeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string brokerId {
        get {
            return this.brokerIdField;
        }
        set {
            this.brokerIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string senderDesc {
        get {
            return this.senderDescField;
        }
        set {
            this.senderDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string senderFiscalCode {
        get {
            return this.senderFiscalCodeField;
        }
        set {
            this.senderFiscalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string hubDesc {
        get {
            return this.hubDescField;
        }
        set {
            this.hubDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("voyage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public shipmentVoyage[] voyage {
        get {
            return this.voyageField;
        }
        set {
            this.voyageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class shipmentVoyage {
    
    private string etaField;
    
    private string sapVoyageNumberField;
    
    private string lmdVoyageNumberField;
    
    private string invoicingDescField;
    
    private shipmentVoyageDoc_header[] doc_headerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string eta {
        get {
            return this.etaField;
        }
        set {
            this.etaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sapVoyageNumber {
        get {
            return this.sapVoyageNumberField;
        }
        set {
            this.sapVoyageNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string lmdVoyageNumber {
        get {
            return this.lmdVoyageNumberField;
        }
        set {
            this.lmdVoyageNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoicingDesc {
        get {
            return this.invoicingDescField;
        }
        set {
            this.invoicingDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("doc_header", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public shipmentVoyageDoc_header[] doc_header {
        get {
            return this.doc_headerField;
        }
        set {
            this.doc_headerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class shipmentVoyageDoc_header {
    
    private string invoiceSerialField;
    
    private string invoiceNumberField;
    
    private string invoiceDateField;
    
    private string invoiceRecipientIdField;
    
    private string invoiceRecipientFiscalCodeField;
    
    private string invoiceRecipientNameField;
    
    private string invoiceRecipientName2Field;
    
    private string invoiceRecipientAddressField;
    
    private string invoiceRecipientAddress2Field;
    
    private string invoiceRecipientZipCodeField;
    
    private string invoiceRecipientTownField;
    
    private string invoiceRecipientCountryField;
    
    private string invoiceRecipientCountryIdField;
    
    private string invoiceRecipientPhoneNumberField;
    
    private string invoiceRecipientFaxField;
    
    private string valueIdField;
    
    private string incotermsIdField;
    
    private string unconditionalDiscountTotalAmountField;
    
    private string conditionalDiscountTotalAmountField;
    
    private string freightTotalAmountField;
    
    private string breakUpOfCostsField;
    
    private string dutyTotalAmountField;
    
    private string taxTotalAmountField;
    
    private string goodsTotalAmountField;
    
    private string invoiceGrossWeightField;
    
    private string invoiceNetWeightField;
    
    private string invoiceBoxesQtyField;
    
    private string paymentTermsDescField;
    
    private string invoiceEffectDateField;
    
    private string financialDocumentReferenceField;
    
    private shipmentVoyageDoc_headerDelivery_header[] delivery_headerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceSerial {
        get {
            return this.invoiceSerialField;
        }
        set {
            this.invoiceSerialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceNumber {
        get {
            return this.invoiceNumberField;
        }
        set {
            this.invoiceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceDate {
        get {
            return this.invoiceDateField;
        }
        set {
            this.invoiceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceRecipientId {
        get {
            return this.invoiceRecipientIdField;
        }
        set {
            this.invoiceRecipientIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceRecipientFiscalCode {
        get {
            return this.invoiceRecipientFiscalCodeField;
        }
        set {
            this.invoiceRecipientFiscalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceRecipientName {
        get {
            return this.invoiceRecipientNameField;
        }
        set {
            this.invoiceRecipientNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceRecipientName2 {
        get {
            return this.invoiceRecipientName2Field;
        }
        set {
            this.invoiceRecipientName2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceRecipientAddress {
        get {
            return this.invoiceRecipientAddressField;
        }
        set {
            this.invoiceRecipientAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceRecipientAddress2 {
        get {
            return this.invoiceRecipientAddress2Field;
        }
        set {
            this.invoiceRecipientAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceRecipientZipCode {
        get {
            return this.invoiceRecipientZipCodeField;
        }
        set {
            this.invoiceRecipientZipCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceRecipientTown {
        get {
            return this.invoiceRecipientTownField;
        }
        set {
            this.invoiceRecipientTownField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceRecipientCountry {
        get {
            return this.invoiceRecipientCountryField;
        }
        set {
            this.invoiceRecipientCountryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceRecipientCountryId {
        get {
            return this.invoiceRecipientCountryIdField;
        }
        set {
            this.invoiceRecipientCountryIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceRecipientPhoneNumber {
        get {
            return this.invoiceRecipientPhoneNumberField;
        }
        set {
            this.invoiceRecipientPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceRecipientFax {
        get {
            return this.invoiceRecipientFaxField;
        }
        set {
            this.invoiceRecipientFaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string valueId {
        get {
            return this.valueIdField;
        }
        set {
            this.valueIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string incotermsId {
        get {
            return this.incotermsIdField;
        }
        set {
            this.incotermsIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string unconditionalDiscountTotalAmount {
        get {
            return this.unconditionalDiscountTotalAmountField;
        }
        set {
            this.unconditionalDiscountTotalAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string conditionalDiscountTotalAmount {
        get {
            return this.conditionalDiscountTotalAmountField;
        }
        set {
            this.conditionalDiscountTotalAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string freightTotalAmount {
        get {
            return this.freightTotalAmountField;
        }
        set {
            this.freightTotalAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string breakUpOfCosts {
        get {
            return this.breakUpOfCostsField;
        }
        set {
            this.breakUpOfCostsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dutyTotalAmount {
        get {
            return this.dutyTotalAmountField;
        }
        set {
            this.dutyTotalAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string taxTotalAmount {
        get {
            return this.taxTotalAmountField;
        }
        set {
            this.taxTotalAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string goodsTotalAmount {
        get {
            return this.goodsTotalAmountField;
        }
        set {
            this.goodsTotalAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceGrossWeight {
        get {
            return this.invoiceGrossWeightField;
        }
        set {
            this.invoiceGrossWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceNetWeight {
        get {
            return this.invoiceNetWeightField;
        }
        set {
            this.invoiceNetWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceBoxesQty {
        get {
            return this.invoiceBoxesQtyField;
        }
        set {
            this.invoiceBoxesQtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string paymentTermsDesc {
        get {
            return this.paymentTermsDescField;
        }
        set {
            this.paymentTermsDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string invoiceEffectDate {
        get {
            return this.invoiceEffectDateField;
        }
        set {
            this.invoiceEffectDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string financialDocumentReference {
        get {
            return this.financialDocumentReferenceField;
        }
        set {
            this.financialDocumentReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("delivery_header", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public shipmentVoyageDoc_headerDelivery_header[] delivery_header {
        get {
            return this.delivery_headerField;
        }
        set {
            this.delivery_headerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class shipmentVoyageDoc_headerDelivery_header {
    
    private string customerIdField;
    
    private string customerFiscalCodeField;
    
    private string customerNameField;
    
    private string customerName2Field;
    
    private string customerAddressField;
    
    private string customerAddress2Field;
    
    private string customerZipCodeField;
    
    private string customerTownField;
    
    private string customerCountryField;
    
    private string customerCountryIdField;
    
    private string customerPhoneNumberField;
    
    private string customerFaxField;
    
    private string deliveryPointIdField;
    
    private string deliveryPointDescField;
    
    private string deliveryPointDesc2Field;
    
    private string deliveryPointCodeAddressField;
    
    private string deliveryPointCodeAddress2Field;
    
    private string deliveryPointCodeZipCodeField;
    
    private string deliveryPointTownField;
    
    private string deliveryPointCountryField;
    
    private string deliveryPointCountryIdField;
    
    private string deliveryPointShopCodeField;
    
    private string deliveryPointPhoneNumberField;
    
    private string deliveryPointFaxField;
    
    private string shopIdField;
    
    private string shopDescField;
    
    private string shopAddressField;
    
    private string shopAddress2Field;
    
    private string shopZipCodeField;
    
    private string shopTownField;
    
    private string shopCountryField;
    
    private string shopCountryIdField;
    
    private string shopPhonNumberField;
    
    private string shopFaxField;
    
    private string boxQtyField;
    
    private string grossWeightField;
    
    private string shippingNoteSerialField;
    
    private string shippingNoteNumberField;
    
    private string shippingNoteDateField;
    
    private string brandDescField;
    
    private shipmentVoyageDoc_headerDelivery_headerBox[] boxField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerId {
        get {
            return this.customerIdField;
        }
        set {
            this.customerIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerFiscalCode {
        get {
            return this.customerFiscalCodeField;
        }
        set {
            this.customerFiscalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerName {
        get {
            return this.customerNameField;
        }
        set {
            this.customerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerName2 {
        get {
            return this.customerName2Field;
        }
        set {
            this.customerName2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerAddress {
        get {
            return this.customerAddressField;
        }
        set {
            this.customerAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerAddress2 {
        get {
            return this.customerAddress2Field;
        }
        set {
            this.customerAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerZipCode {
        get {
            return this.customerZipCodeField;
        }
        set {
            this.customerZipCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerTown {
        get {
            return this.customerTownField;
        }
        set {
            this.customerTownField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerCountry {
        get {
            return this.customerCountryField;
        }
        set {
            this.customerCountryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerCountryId {
        get {
            return this.customerCountryIdField;
        }
        set {
            this.customerCountryIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerPhoneNumber {
        get {
            return this.customerPhoneNumberField;
        }
        set {
            this.customerPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customerFax {
        get {
            return this.customerFaxField;
        }
        set {
            this.customerFaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliveryPointId {
        get {
            return this.deliveryPointIdField;
        }
        set {
            this.deliveryPointIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliveryPointDesc {
        get {
            return this.deliveryPointDescField;
        }
        set {
            this.deliveryPointDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliveryPointDesc2 {
        get {
            return this.deliveryPointDesc2Field;
        }
        set {
            this.deliveryPointDesc2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliveryPointCodeAddress {
        get {
            return this.deliveryPointCodeAddressField;
        }
        set {
            this.deliveryPointCodeAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliveryPointCodeAddress2 {
        get {
            return this.deliveryPointCodeAddress2Field;
        }
        set {
            this.deliveryPointCodeAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliveryPointCodeZipCode {
        get {
            return this.deliveryPointCodeZipCodeField;
        }
        set {
            this.deliveryPointCodeZipCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliveryPointTown {
        get {
            return this.deliveryPointTownField;
        }
        set {
            this.deliveryPointTownField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliveryPointCountry {
        get {
            return this.deliveryPointCountryField;
        }
        set {
            this.deliveryPointCountryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliveryPointCountryId {
        get {
            return this.deliveryPointCountryIdField;
        }
        set {
            this.deliveryPointCountryIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliveryPointShopCode {
        get {
            return this.deliveryPointShopCodeField;
        }
        set {
            this.deliveryPointShopCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliveryPointPhoneNumber {
        get {
            return this.deliveryPointPhoneNumberField;
        }
        set {
            this.deliveryPointPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deliveryPointFax {
        get {
            return this.deliveryPointFaxField;
        }
        set {
            this.deliveryPointFaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shopId {
        get {
            return this.shopIdField;
        }
        set {
            this.shopIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shopDesc {
        get {
            return this.shopDescField;
        }
        set {
            this.shopDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shopAddress {
        get {
            return this.shopAddressField;
        }
        set {
            this.shopAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shopAddress2 {
        get {
            return this.shopAddress2Field;
        }
        set {
            this.shopAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shopZipCode {
        get {
            return this.shopZipCodeField;
        }
        set {
            this.shopZipCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shopTown {
        get {
            return this.shopTownField;
        }
        set {
            this.shopTownField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shopCountry {
        get {
            return this.shopCountryField;
        }
        set {
            this.shopCountryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shopCountryId {
        get {
            return this.shopCountryIdField;
        }
        set {
            this.shopCountryIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shopPhonNumber {
        get {
            return this.shopPhonNumberField;
        }
        set {
            this.shopPhonNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shopFax {
        get {
            return this.shopFaxField;
        }
        set {
            this.shopFaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string boxQty {
        get {
            return this.boxQtyField;
        }
        set {
            this.boxQtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string grossWeight {
        get {
            return this.grossWeightField;
        }
        set {
            this.grossWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shippingNoteSerial {
        get {
            return this.shippingNoteSerialField;
        }
        set {
            this.shippingNoteSerialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shippingNoteNumber {
        get {
            return this.shippingNoteNumberField;
        }
        set {
            this.shippingNoteNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shippingNoteDate {
        get {
            return this.shippingNoteDateField;
        }
        set {
            this.shippingNoteDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string brandDesc {
        get {
            return this.brandDescField;
        }
        set {
            this.brandDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("box", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public shipmentVoyageDoc_headerDelivery_headerBox[] box {
        get {
            return this.boxField;
        }
        set {
            this.boxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class shipmentVoyageDoc_headerDelivery_headerBox {
    
    private string boxIdField;
    
    private string boxGrossWeightField;
    
    private string boxVolumeField;
    
    private shipmentVoyageDoc_headerDelivery_headerBoxDelivery_detail[] delivery_detailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string boxId {
        get {
            return this.boxIdField;
        }
        set {
            this.boxIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string boxGrossWeight {
        get {
            return this.boxGrossWeightField;
        }
        set {
            this.boxGrossWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string boxVolume {
        get {
            return this.boxVolumeField;
        }
        set {
            this.boxVolumeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("delivery_detail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public shipmentVoyageDoc_headerDelivery_headerBoxDelivery_detail[] delivery_detail {
        get {
            return this.delivery_detailField;
        }
        set {
            this.delivery_detailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class shipmentVoyageDoc_headerDelivery_headerBoxDelivery_detail {
    
    private string styleIdField;
    
    private string styleDescField;
    
    private string seasonYearIdField;
    
    private string seasonIdField;
    
    private string themeListField;
    
    private string fromToSizeIdField;
    
    private string unitOfMeasurementIdField;
    
    private string piecesQtyField;
    
    private string unitInvoicingPriceField;
    
    private string styleCompositionDescField;
    
    private string extendedStyleCompositionDescField;
    
    private string extendedStyleDescField;
    
    private string madeInIdField;
    
    private string notPreferentialIdField;
    
    private string netWeightField;
    
    private string processingIdField;
    
    private string processingDescField;
    
    private string genderIdField;
    
    private string genderDescField;
    
    private string customsCodeExportField;
    
    private string productIdField;
    
    private string orderRefField;
    
    private string articleRefField;
    
    private shipmentVoyageDoc_headerDelivery_headerBoxDelivery_detailSku[] skuField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string styleId {
        get {
            return this.styleIdField;
        }
        set {
            this.styleIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string styleDesc {
        get {
            return this.styleDescField;
        }
        set {
            this.styleDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string seasonYearId {
        get {
            return this.seasonYearIdField;
        }
        set {
            this.seasonYearIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string seasonId {
        get {
            return this.seasonIdField;
        }
        set {
            this.seasonIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string themeList {
        get {
            return this.themeListField;
        }
        set {
            this.themeListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fromToSizeId {
        get {
            return this.fromToSizeIdField;
        }
        set {
            this.fromToSizeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string unitOfMeasurementId {
        get {
            return this.unitOfMeasurementIdField;
        }
        set {
            this.unitOfMeasurementIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string piecesQty {
        get {
            return this.piecesQtyField;
        }
        set {
            this.piecesQtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string unitInvoicingPrice {
        get {
            return this.unitInvoicingPriceField;
        }
        set {
            this.unitInvoicingPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string styleCompositionDesc {
        get {
            return this.styleCompositionDescField;
        }
        set {
            this.styleCompositionDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string extendedStyleCompositionDesc {
        get {
            return this.extendedStyleCompositionDescField;
        }
        set {
            this.extendedStyleCompositionDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string extendedStyleDesc {
        get {
            return this.extendedStyleDescField;
        }
        set {
            this.extendedStyleDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string madeInId {
        get {
            return this.madeInIdField;
        }
        set {
            this.madeInIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string notPreferentialId {
        get {
            return this.notPreferentialIdField;
        }
        set {
            this.notPreferentialIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string netWeight {
        get {
            return this.netWeightField;
        }
        set {
            this.netWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string processingId {
        get {
            return this.processingIdField;
        }
        set {
            this.processingIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string processingDesc {
        get {
            return this.processingDescField;
        }
        set {
            this.processingDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string genderId {
        get {
            return this.genderIdField;
        }
        set {
            this.genderIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string genderDesc {
        get {
            return this.genderDescField;
        }
        set {
            this.genderDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customsCodeExport {
        get {
            return this.customsCodeExportField;
        }
        set {
            this.customsCodeExportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string productId {
        get {
            return this.productIdField;
        }
        set {
            this.productIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string orderRef {
        get {
            return this.orderRefField;
        }
        set {
            this.orderRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string articleRef {
        get {
            return this.articleRefField;
        }
        set {
            this.articleRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sku", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public shipmentVoyageDoc_headerDelivery_headerBoxDelivery_detailSku[] sku {
        get {
            return this.skuField;
        }
        set {
            this.skuField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class shipmentVoyageDoc_headerDelivery_headerBoxDelivery_detailSku {
    
    private string sizeIdField;
    
    private string userCategoryIdField;
    
    private string userCategoryDescField;
    
    private string colorIdField;
    
    private string eanCodeIdField;
    
    private string skuNetWeightField;
    
    private string skuPiecesQtyField;
    
    private string salePriceCurrencyField;
    
    private string salePriceField;
    
    private string manufacturerDescField;
    
    private string manufacturerDesc2Field;
    
    private string manufacturerAddressField;
    
    private string manufacturerAddress2Field;
    
    private string manufacturerZipCodeField;
    
    private string manufacturerCountryField;
    
    private string manufacturerCountryIdField;
    
    private string manufacturerEmailField;
    
    private string manufacturerMidField;
    
    private string manufacturerPhoneNumberField;
    
    private string manufacturerFaxField;
    
    private string customsCodeImportField;
    
    private string vatTypeIdField;
    
    private string firstInvoiceValueField;
    
    private string firstInvoicePriceField;
    
    private string sellingValueIdField;
    
    private string unitSellingPriceField;
    
    private string carryOverFlagField;
    
    private string sellOutSeasonField;
    
    private string vatCodeIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sizeId {
        get {
            return this.sizeIdField;
        }
        set {
            this.sizeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userCategoryId {
        get {
            return this.userCategoryIdField;
        }
        set {
            this.userCategoryIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string userCategoryDesc {
        get {
            return this.userCategoryDescField;
        }
        set {
            this.userCategoryDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string colorId {
        get {
            return this.colorIdField;
        }
        set {
            this.colorIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string eanCodeId {
        get {
            return this.eanCodeIdField;
        }
        set {
            this.eanCodeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string skuNetWeight {
        get {
            return this.skuNetWeightField;
        }
        set {
            this.skuNetWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string skuPiecesQty {
        get {
            return this.skuPiecesQtyField;
        }
        set {
            this.skuPiecesQtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string salePriceCurrency {
        get {
            return this.salePriceCurrencyField;
        }
        set {
            this.salePriceCurrencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string salePrice {
        get {
            return this.salePriceField;
        }
        set {
            this.salePriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string manufacturerDesc {
        get {
            return this.manufacturerDescField;
        }
        set {
            this.manufacturerDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string manufacturerDesc2 {
        get {
            return this.manufacturerDesc2Field;
        }
        set {
            this.manufacturerDesc2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string manufacturerAddress {
        get {
            return this.manufacturerAddressField;
        }
        set {
            this.manufacturerAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string manufacturerAddress2 {
        get {
            return this.manufacturerAddress2Field;
        }
        set {
            this.manufacturerAddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string manufacturerZipCode {
        get {
            return this.manufacturerZipCodeField;
        }
        set {
            this.manufacturerZipCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string manufacturerCountry {
        get {
            return this.manufacturerCountryField;
        }
        set {
            this.manufacturerCountryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string manufacturerCountryId {
        get {
            return this.manufacturerCountryIdField;
        }
        set {
            this.manufacturerCountryIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string manufacturerEmail {
        get {
            return this.manufacturerEmailField;
        }
        set {
            this.manufacturerEmailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string manufacturerMid {
        get {
            return this.manufacturerMidField;
        }
        set {
            this.manufacturerMidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string manufacturerPhoneNumber {
        get {
            return this.manufacturerPhoneNumberField;
        }
        set {
            this.manufacturerPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string manufacturerFax {
        get {
            return this.manufacturerFaxField;
        }
        set {
            this.manufacturerFaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string customsCodeImport {
        get {
            return this.customsCodeImportField;
        }
        set {
            this.customsCodeImportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string vatTypeId {
        get {
            return this.vatTypeIdField;
        }
        set {
            this.vatTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string firstInvoiceValue {
        get {
            return this.firstInvoiceValueField;
        }
        set {
            this.firstInvoiceValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string firstInvoicePrice {
        get {
            return this.firstInvoicePriceField;
        }
        set {
            this.firstInvoicePriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sellingValueId {
        get {
            return this.sellingValueIdField;
        }
        set {
            this.sellingValueIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string unitSellingPrice {
        get {
            return this.unitSellingPriceField;
        }
        set {
            this.unitSellingPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string carryOverFlag {
        get {
            return this.carryOverFlagField;
        }
        set {
            this.carryOverFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sellOutSeason {
        get {
            return this.sellOutSeasonField;
        }
        set {
            this.sellOutSeasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string vatCodeId {
        get {
            return this.vatCodeIdField;
        }
        set {
            this.vatCodeIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private shipment[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shipment")]
    public shipment[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
